#+TITLE: Mujer desierto
#+AUTHOR: laertida
#+EMAIL: laertida@protonmail.com
#+DATE: 2022-06-22
#+LANGUAGE: es
#+OPTIONS:  toc:nil date:t creator:t email:nil author:t html-style:nil
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="/css/main.css" />

/A Sofía/

*

Hay tierras fértiles al centro y al sur

donde la lluvia no para y huele a maíz,

pero yo quiero ir al Norte

allá donde la tierra quema igual que el sol

y la piel arde nomás de saberse a la interperie

donde el agua no calma la sed y las yerbas no crecen.

**

¿A qué vas, viajero, allá?

Me preguntan quienes solo auguran desventuras

Allá está ella, allá voy yo

voy siguiendo el árido aroma de la ilusión,

voy buscando mi mujer desierto...

*

Quiero estar con ella, quiero ser con ella

Estar en el pesado calor de su tarde, ser el viento de su cabello

Estar en el atardecer de sus ojitos, ser el calor de de sus cobijas

Estar en la lluvia de su tierra, ser la arena de su playa.

**

Recorreré durante el día la arena de su cuerpo

con pasos resbalosos con los que no se avanza

taparme con las manos el brillo del sol

que el suelo derrita mis zapatos

y el sopor se lleve mi aliento.

Mi corazón me hará lograrlo sin sed ni cansancio.

*

Me guiaré en la noche con sus lunares

Haré mapas estelares y nombraré constelaciones

Descubriré las leyes de sus astros

haré horóscopos con sus ciclos

predeciré los eclipses y los solsticios

y mi alma me bastará para  hacerlo sin frío ni tristeza.

**

Y cuando por fin me plante frente a ella le diré:

¡Yo creo!

Toma mi mano, cree conmigo

¡Yo creo!

Toma mi mano, crea conmigo

que el mundo será lo que crearemos

que lo transformaremos en lo que creemos

que en nuestro amor se formarán planicies

crecerán los cactus y rodarán las plantas

la lluvia caerá para dar de beber a las lagartijas

hará que los alacranes inyecten miel

hará que las serpientes canten y los venados bailen.

que el amor que tú y yo forjaremos

será el paraíso a cincuenta grados.
